version: '3.8'

services:
  egg-timer-app:
    image: ${DOCKER_REGISTRY}/egg-timer-app:${VERSION}
    container_name: egg-timer-app-staging
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - egg-timer-network

networks:
  egg-timer-network:
    driver: bridge 